"""add subscriptions table

Revision ID: f3e8118b10a7
Revises: fix_telegram_id_type
Create Date: 2026-04-03 02:28:59.253700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f3e8118b10a7'
down_revision: Union[str, None] = 'fix_telegram_id_type'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First drop default values (sequences) from ID columns - they can't be cast to UUID
    op.alter_column('users', 'id', existing_server_default=sa.text("nextval('users_id_seq')"), server_default=None)
    op.alter_column('payments', 'id', existing_server_default=sa.text("nextval('payments_id_seq')"), server_default=None)
    op.alter_column('referral_earnings', 'id', existing_server_default=sa.text("nextval('referral_earnings_id_seq')"), server_default=None)
    
    # Drop ALL foreign key constraints
    op.drop_constraint('payments_user_id_fkey', 'payments', type_='foreignkey')
    op.drop_constraint('referral_earnings_referrer_id_fkey', 'referral_earnings', type_='foreignkey')
    op.drop_constraint('referral_earnings_referral_id_fkey', 'referral_earnings', type_='foreignkey')
    op.drop_constraint('referral_earnings_payment_id_fkey', 'referral_earnings', type_='foreignkey')
    op.drop_constraint('users_referred_by_id_fkey', 'users', type_='foreignkey')
    
    # Convert users.id to UUID
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using="lpad(id::text, 32, '0')::uuid")
    
    # Convert referred_by_id to UUID
    op.alter_column('users', 'referred_by_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=True,
               postgresql_using="lpad(referred_by_id::text, 32, '0')::uuid")
    
    # Convert payments.id and user_id to UUID
    op.alter_column('payments', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using="lpad(id::text, 32, '0')::uuid")
    op.alter_column('payments', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using="lpad(user_id::text, 32, '0')::uuid")
    
    # Convert referral_earnings columns to UUID
    op.alter_column('referral_earnings', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using="lpad(id::text, 32, '0')::uuid")
    op.alter_column('referral_earnings', 'referrer_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using="lpad(referrer_id::text, 32, '0')::uuid")
    op.alter_column('referral_earnings', 'referral_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using="lpad(referral_id::text, 32, '0')::uuid")
    op.alter_column('referral_earnings', 'payment_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using="lpad(payment_id::text, 32, '0')::uuid")
    
    # Recreate ALL foreign key constraints with UUID types
    op.create_foreign_key('users_referred_by_id_fkey', 'users', 'users', 
                         ['referred_by_id'], ['id'])
    op.create_foreign_key('payments_user_id_fkey', 'payments', 'users', 
                         ['user_id'], ['id'])
    op.create_foreign_key('referral_earnings_referrer_id_fkey', 'referral_earnings', 'users',
                         ['referrer_id'], ['id'])
    op.create_foreign_key('referral_earnings_referral_id_fkey', 'referral_earnings', 'users',
                         ['referral_id'], ['id'])
    op.create_foreign_key('referral_earnings_payment_id_fkey', 'referral_earnings', 'payments',
                         ['payment_id'], ['id'])
    
    # Create subscriptions table with foreign key to users.id
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('device_limit', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop all tables in reverse order (with foreign keys)
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    
    op.drop_index(op.f('ix_referral_earnings_referral_id'), table_name='referral_earnings')
    op.drop_index(op.f('ix_referral_earnings_referrer_id'), table_name='referral_earnings')
    op.drop_index(op.f('ix_referral_earnings_id'), table_name='referral_earnings')
    op.drop_table('referral_earnings')
    
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###